[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Ensure devDependencies (like TypeScript) are installed in Netlify
  NPM_FLAGS = "--include=dev"

# No redirects overriding Next.js routing; Netlify Next adapter handles routing

# Configuración para Next.js
[functions]
  external_node_modules = ["sharp"]

# Variables de entorno para producción
[context.production.environment]
  NODE_ENV = "production"

# Configuración para deploy previews
[context.deploy-preview.environment]
  NODE_ENV = "production"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"